'use client'

import { useState } from 'react'

interface SEOAnalysisProps {
  content: any // Portable Text content
  title: string
  existingTags?: string[]
  className?: string
}

interface SEOResult {
  metaTitle: string
  metaDescription: string
  keywords: string[]
  seoScore: number
  suggestions: string[]
  readingTime: number
  autoGeneratedTags: string[]
  analysis: any
}

const SEOAnalysis = ({ content, title, existingTags = [], className = '' }: SEOAnalysisProps) => {
  const [seoResult, setSeoResult] = useState<SEOResult | null>(null)
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [activeTab, setActiveTab] = useState<'overview' | 'keywords' | 'suggestions' | 'technical'>('overview')

  // Portable Textコンテンツをプレーンテキストに変換
  const convertPortableTextToString = (content: any): string => {
    if (!content) return ''
    
    return content.map((block: any) => {
      if (block._type === 'block') {
        return block.children?.map((child: any) => child.text).join('') || ''
      }
      return ''
    }).join(' ')
  }

  const performSEOAnalysis = async () => {
    setIsAnalyzing(true)
    try {
      const textContent = convertPortableTextToString(content)
      
      const response = await fetch('/api/seo-analysis', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title,
          content: textContent,
          existingTags
        })
      })

      if (!response.ok) {
        throw new Error('Failed to perform SEO analysis')
      }

      const result = await response.json()
      setSeoResult(result)
    } catch (error) {
      console.error('Error performing SEO analysis:', error)
    } finally {
      setIsAnalyzing(false)
    }
  }

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-white bg-green-500'
    if (score >= 60) return 'text-white bg-navy-300'
    return 'text-white bg-zinc-400'
  }

  const getScoreLabel = (score: number) => {
    if (score >= 80) return 'EXCELLENT'
    if (score >= 60) return 'GOOD'
    if (score >= 40) return 'NEED WORK'
    return 'CRITICAL'
  }

  return (
    <div className={`bg-white border border-zinc-200 shadow-2xl ${className}`}>
      <div className="p-10 border-b border-zinc-100 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-8">
        <div>
          <div className="flex items-center space-x-3 mb-3">
            <span className="w-10 h-10 bg-navy-500 flex items-center justify-center text-white text-[10px] font-black font-outfit uppercase tracking-tighter">SEO</span>
            <h3 className="text-2xl font-black text-navy-500 tracking-tighter uppercase font-outfit">Optimization</h3>
          </div>
          <p className="text-[10px] text-zinc-400 font-bold tracking-[0.3em] uppercase">
            アルゴリズムに基づき、記事のパフォーマンスを分析します
          </p>
        </div>
        <button
          onClick={performSEOAnalysis}
          disabled={isAnalyzing}
          className={`flex items-center px-10 py-5 text-[10px] font-black tracking-[0.4em] uppercase transition-all duration-500 ${
            isAnalyzing
              ? 'bg-zinc-100 text-zinc-400 cursor-not-allowed'
              : 'bg-navy-500 text-white hover:bg-navy-600 shadow-2xl'
          }`}
        >
          {isAnalyzing ? (
            <div className="flex items-center space-x-3">
              <div className="w-4 h-4 border-2 border-zinc-400 border-t-transparent rounded-full animate-spin"></div>
              <span>Analyzing...</span>
            </div>
          ) : (
            <>
              <i className="ri-rocket-2-line mr-3 text-lg" />
              Analyze Post
            </>
          )}
        </button>
      </div>

      {seoResult && (
        <div>
          {/* タブナビゲーション */}
          <div className="flex border-b border-zinc-100 bg-zinc-50">
            {[
              { key: 'overview', label: 'Overview', icon: 'ri-dashboard-line' },
              { key: 'keywords', label: 'Keywords', icon: 'ri-key-2-line' },
              { key: 'suggestions', label: 'Insight', icon: 'ri-lightbulb-line' },
              { key: 'technical', label: 'Technical', icon: 'ri-settings-3-line' }
            ].map(tab => (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key as any)}
                className={`flex-1 py-5 px-6 text-[10px] font-black tracking-widest uppercase transition-all duration-500 flex items-center justify-center ${
                  activeTab === tab.key
                    ? 'bg-white text-navy-500 border-b-2 border-navy-500'
                    : 'text-zinc-400 hover:text-navy-300 hover:bg-white'
                }`}
              >
                <i className={`${tab.icon} mr-3 text-sm`} />
                {tab.label}
              </button>
            ))}
          </div>

          <div className="p-10">
            {/* 概要タブ */}
            {activeTab === 'overview' && (
              <div className="space-y-12">
                <div className="text-center">
                  <div className={`inline-flex flex-col items-center p-12 w-48 h-48 rounded-full border-4 border-white shadow-2xl justify-center ${getScoreColor(seoResult.seoScore)}`}>
                    <div className="text-4xl font-black font-outfit mb-2">{seoResult.seoScore}</div>
                    <div className="text-[8px] font-black tracking-[0.2em]">{getScoreLabel(seoResult.seoScore)}</div>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                  {[
                    { i: 'ri-time-line', l: 'READ TIME', v: `${seoResult.readingTime} min` },
                    { i: 'ri-price-tag-3-line', l: 'TAGS', v: `${seoResult.autoGeneratedTags.length} items` },
                    { i: 'ri-text-spacing', l: 'WORDS', v: seoResult.analysis.contentAnalysis.wordCount }
                  ].map(stat => (
                    <div key={stat.l} className="bg-zinc-50 p-6 text-center border border-zinc-100">
                      <i className={`${stat.i} text-navy-200 text-2xl mb-3 block`} />
                      <div className="text-[8px] text-zinc-400 font-black tracking-widest mb-1">{stat.l}</div>
                      <div className="text-xl font-black text-navy-500 font-outfit tracking-tighter">{stat.v}</div>
                    </div>
                  ))}
                </div>

                <div className="bg-zinc-950 p-8 text-white">
                  <h4 className="text-[10px] font-black tracking-[0.4em] uppercase mb-6 flex items-center">
                    <i className="ri-google-fill mr-3 text-lg" />
                    SERP Preview
                  </h4>
                  <div className="space-y-2 border-l-2 border-navy-500 pl-6">
                    <div className="text-blue-400 text-lg font-bold line-clamp-1">{seoResult.metaTitle}</div>
                    <div className="text-zinc-500 text-[10px] tracking-widest uppercase">junya-official-site.com</div>
                    <div className="text-zinc-400 text-xs leading-relaxed line-clamp-2">{seoResult.metaDescription}</div>
                  </div>
                </div>
              </div>
            )}

            {activeTab === 'keywords' && (
              <div className="space-y-12">
                {[
                  { l: 'Primary Keywords', k: seoResult.analysis.keywordAnalysis.primaryKeywords, c: 'bg-navy-500 text-white' },
                  { l: 'Secondary Keywords', k: seoResult.analysis.keywordAnalysis.secondaryKeywords, c: 'bg-zinc-100 text-navy-400' },
                  { l: 'Long Tail Strategy', k: seoResult.analysis.keywordAnalysis.longTailKeywords, c: 'bg-zinc-50 text-zinc-400 border border-zinc-100' }
                ].map(group => (
                  <div key={group.l}>
                    <h4 className="text-[10px] font-black text-navy-500 tracking-[0.4em] uppercase mb-6">{group.l}</h4>
                    <div className="flex flex-wrap gap-3">
                      {group.k.map((keyword: string, index: number) => (
                        <span key={index} className={`px-6 py-2 text-[10px] font-black tracking-widest uppercase ${group.c}`}>
                          {keyword}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {activeTab === 'suggestions' && (
              <div className="space-y-6">
                <h4 className="text-[10px] font-black text-navy-500 tracking-[0.4em] uppercase mb-8">AI Insights</h4>
                {seoResult.suggestions.map((suggestion, index) => (
                  <div key={index} className="flex items-start space-x-6 p-6 bg-zinc-50 border border-zinc-100 hover:border-navy-500 transition-colors">
                    <i className="ri-lightbulb-flash-line text-navy-300 text-xl" />
                    <span className="text-sm text-navy-500 font-medium leading-loose">{suggestion}</span>
                  </div>
                ))}
              </div>
            )}

            {activeTab === 'technical' && (
              <div className="space-y-12">
                <div>
                  <h4 className="text-[10px] font-black text-navy-500 tracking-[0.4em] uppercase mb-6">Asset Structure</h4>
                  <div className="grid grid-cols-2 gap-6">
                    <div className="bg-zinc-50 p-6 border border-zinc-100 text-center">
                      <div className="text-[8px] text-zinc-400 font-black tracking-widest mb-1 uppercase">Paragraphs</div>
                      <div className="text-3xl font-black text-navy-500 font-outfit">{seoResult.analysis.contentAnalysis.paragraphCount}</div>
                    </div>
                    <div className="bg-zinc-50 p-6 border border-zinc-100 text-center">
                      <div className="text-[8px] text-zinc-400 font-black tracking-widest mb-1 uppercase">Headings</div>
                      <div className="text-3xl font-black text-navy-500 font-outfit">{seoResult.analysis.contentAnalysis.headingCount}</div>
                    </div>
                  </div>
                </div>

                <div className="space-y-8">
                  <h4 className="text-[10px] font-black text-navy-500 tracking-[0.4em] uppercase mb-6">Metadata Audit</h4>
                  <div className="space-y-6">
                    <div>
                      <div className="flex justify-between items-end mb-3">
                        <label className="text-[10px] font-black text-zinc-400 tracking-widest uppercase">Meta Title</label>
                        <span className="text-[8px] font-black font-outfit text-navy-300">{seoResult.metaTitle.length}/60</span>
                      </div>
                      <div className="p-4 bg-zinc-50 border border-zinc-100 text-[10px] font-mono text-navy-400">{seoResult.metaTitle}</div>
                    </div>
                    <div>
                      <div className="flex justify-between items-end mb-3">
                        <label className="text-[10px] font-black text-zinc-400 tracking-widest uppercase">Meta Description</label>
                        <span className="text-[8px] font-black font-outfit text-navy-300">{seoResult.metaDescription.length}/160</span>
                      </div>
                      <div className="p-4 bg-zinc-50 border border-zinc-100 text-[10px] font-mono text-navy-400 leading-relaxed">{seoResult.metaDescription}</div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

export default SEOAnalysis